# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kyfo(object):
    def setupUi(self, Kyfo):
        Kyfo.setObjectName("Kyfo")
        Kyfo.resize(203, 278)
        Kyfo.setAcceptDrops(True)
        Kyfo.setWindowTitle("Kyfo")
        self.centralwidget = QtWidgets.QWidget(Kyfo)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 210, 121, 21))
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 210, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 35, 10))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 30, 181, 171))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 210, 21, 21))
        self.pushButton.setObjectName("pushButton")
        Kyfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Kyfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 203, 18))
        self.menubar.setObjectName("menubar")
        Kyfo.setMenuBar(self.menubar)

        self.retranslateUi(Kyfo)
        QtCore.QMetaObject.connectSlotsByName(Kyfo)

    def retranslateUi(self, Kyfo):
        _translate = QtCore.QCoreApplication.translate
        self.plainTextEdit.setPlainText(_translate("Kyfo", "comands"))
        self.label.setText(_translate("Kyfo", "Input"))
        self.label_2.setText(_translate("Kyfo", "Output"))
        self.pushButton.setText(_translate("Kyfo", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kyfo = QtWidgets.QMainWindow()
    ui = Ui_Kyfo()
    ui.setupUi(Kyfo)
    Kyfo.show()
    sys.exit(app.exec_())
