/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kyfo;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author herni
 */
public class gui extends javax.swing.JFrame {    
    
    /**
     * Creates new form 
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualRute = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        updateImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KYFO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        actualRute.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        actualRute.setText("Rute");
        actualRute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualRuteActionPerformed(evt);
            }
        });

        imagen.setBackground(new java.awt.Color(204, 204, 204));
        imagen.setForeground(new java.awt.Color(204, 204, 204));
        imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\herni\\OneDrive\\Documentos\\GitHub\\KYFO\\Cat03.jpg")); // NOI18N

        updateImagen.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        updateImagen.setText("Get Image");
        updateImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actualRute)
                        .addGap(18, 18, 18)
                        .addComponent(updateImagen)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualRute)
                    .addComponent(updateImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void actualRuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualRuteActionPerformed
        Object[] options = {"Yes", "No", "Reset Rute"};
        int opt;
        do {
            String ruteDialog = "The actual rute is: " + Globals.actualRute + "\nDo you want to change it?";
            opt = JOptionPane.showOptionDialog(this, ruteDialog, "Actual Rute",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            switch (opt) {
                case 0:
                    Globals.actualRute = JOptionPane.showInputDialog("Enter the new complete rute:", Globals.actualRute);
                    break;
                case 1:
                    break;
                case 2:
                    Globals.actualRute = Commands.getRute();
                    break;
                default:
                    throw new AssertionError();
            }
            if(opt == 0){
                
            }
        } while (opt != 1);
    }//GEN-LAST:event_actualRuteActionPerformed

    private void updateImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateImagenActionPerformed
        imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\herni\\OneDrive\\Documentos\\GitHub\\KYFO\\Cat.jpg"));
    }//GEN-LAST:event_updateImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualRute;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton updateImagen;
    // End of variables declaration//GEN-END:variables
}
